# Generated by Django 5.0 on 2024-05-01 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=50, verbose_name='Специализация')),
            ],
        ),
        migrations.CreateModel(
            name='HR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='upload/resume', verbose_name='Готовое резюме')),
                ('stage', models.CharField(choices=[('Создание анкеты', 'Создание анкеты'), ('Рассмотрение анкеты', 'Рассмотрение анкеты'), ('Первичное интервью', 'Первичное интервью'), ('3', 'Интервью с заказчиком'), ('4', 'Сбор рекомендаций'), ('5', 'Оффер'), ('6', 'Трудоустройство')], default='Создание анкеты', max_length=50)),
                ('hr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_application.hr')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.IntegerField(verbose_name='Зарплата')),
                ('busyness', models.CharField(max_length=50, verbose_name='Занятость')),
                ('work_schedule', models.CharField(max_length=50, verbose_name='График работы')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_application.job')),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_application.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/', verbose_name='Портфолио')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_application.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('native', models.CharField(choices=[('Русский', 'Русский'), ('Английский', 'Английский')], max_length=50, verbose_name='Родной язык')),
                ('list_languages', models.CharField(choices=[('Русский', 'Русский'), ('Английский', 'Английский')], max_length=50, null=True, verbose_name='Иностранные языки')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_application.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lvl', models.CharField(choices=[('Высшее образование', 'Высшее образование')], max_length=50, verbose_name='Уровень')),
                ('lvl_university', models.CharField(max_length=50, verbose_name='Учебное заведение')),
                ('faculty', models.CharField(max_length=50, verbose_name='Факультет')),
                ('specialization', models.CharField(max_length=50, verbose_name='Специализация')),
                ('year_graduatio', models.IntegerField(verbose_name='Год окончания')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_application.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_course', models.CharField(max_length=100, verbose_name='Название курса')),
                ('organization', models.CharField(max_length=100, verbose_name='Проводившая организация')),
                ('specialization', models.CharField(max_length=100, verbose_name='Специализация')),
                ('year_graduation', models.IntegerField(verbose_name='Год окончания')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_application.resume')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Москва', 'Москва')], max_length=50, verbose_name='Название города')),
                ('resume', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_application.resume')),
            ],
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Обо мне')),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_application.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(choices=[('Python', 'Python')], max_length=50, verbose_name='Список skills')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_application.resume')),
            ],
        ),
    ]
