# Generated by Django 5.0 on 2024-04-20 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name_course',
            field=models.CharField(max_length=100, verbose_name='Название курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='organization',
            field=models.CharField(max_length=100, verbose_name='Проводившая организация'),
        ),
        migrations.AlterField(
            model_name='course',
            name='specialization',
            field=models.CharField(max_length=100, verbose_name='Специализация'),
        ),
        migrations.AlterField(
            model_name='education',
            name='faculty',
            field=models.CharField(max_length=50, verbose_name='Факультет'),
        ),
        migrations.AlterField(
            model_name='education',
            name='lvl_university',
            field=models.CharField(max_length=50, verbose_name='Учебное заведение'),
        ),
        migrations.AlterField(
            model_name='education',
            name='specialization',
            field=models.CharField(max_length=50, verbose_name='Специализация'),
        ),
        migrations.AlterField(
            model_name='languages',
            name='list_languages',
            field=models.CharField(max_length=50, verbose_name='Иностранные языки'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='stage',
            field=models.CharField(choices=[('Создание анкеты', 'Создание анкеты'), ('Рассмотрение анкеты', 'Рассмотрение анкеты'), ('Первичное интервью', 'Первичное интервью'), ('3', 'Интервью с заказчиком'), ('4', 'Сбор рекомендаций'), ('5', 'Оффер'), ('6', 'Трудоустройство')], default='Создание анкеты', max_length=50),
        ),
    ]
