# Generated by Django 4.2.5 on 2024-04-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number_phone',
            field=models.IntegerField(null=True, verbose_name='Номер телефона'),
        ),
    ]
